# Generated by Django 2.2.4 on 2019-08-14 08:10

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_seed_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Agregado'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='desc',
            field=models.TextField(blank=True, help_text='Completar especialmente si fue una llamada', null=True, verbose_name='Descripción o comentarios al respecto'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='numero',
            field=models.CharField(help_text='Podés ingresar como 09XXXXXXXX, 5959XXXXXXXX o +5959XXXXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='screenshot',
            field=models.ImageField(help_text='Si fue una llamada hacer captura del registro de llamadas', upload_to=backend.models.rename, verbose_name='Captura de pantalla'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Título de la Estadística'),
        ),
    ]
